# Generated by Django 5.0.2 on 2025-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('authors', models.JSONField(default=list)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('released', models.DateTimeField()),
                ('cover_base64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
