# Generated by Django 5.0.2 on 2025-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='character_books', to='characters.character'),
        ),
        migrations.AddField(
            model_name='book',
            name='pov_characters',
            field=models.ManyToManyField(blank=True, related_name='character_pov_books', to='characters.character'),
        ),
    ]
