# Generated by Django 5.0.2 on 2025-04-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_links',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
