# Generated by Django 5.0.2 on 2025-04-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_book_amazon_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='amazon_links',
            new_name='amazon_link',
        ),
    ]
