# Generated by Django 5.0.2 on 2025-04-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_of_arms', models.TextField(blank=True, null=True)),
                ('words', models.CharField(blank=True, max_length=255, null=True)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('seats', models.JSONField(blank=True, default=list)),
                ('founded', models.CharField(blank=True, max_length=255, null=True)),
                ('died_out', models.CharField(blank=True, max_length=255, null=True)),
                ('ancestral_weapons', models.JSONField(blank=True, default=list)),
                ('cadet_branches', models.ManyToManyField(blank=True, related_name='parent_houses', to='houses.house')),
                ('current_lord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_lord_of', to='characters.character')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founded_houses', to='characters.character')),
                ('heir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heir_of', to='characters.character')),
                ('overlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vassals', to='houses.house')),
                ('sworn_members', models.ManyToManyField(blank=True, related_name='sworn_houses', to='characters.character')),
            ],
        ),
    ]
