# Generated by Django 5.0.2 on 2025-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('culture', models.CharField(blank=True, max_length=255, null=True)),
                ('born', models.CharField(blank=True, max_length=255, null=True)),
                ('died', models.CharField(blank=True, max_length=255, null=True)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('tv_series', models.JSONField(blank=True, default=list)),
                ('played_by', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
