# Generated by Django 5.0.2 on 2025-04-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('characters', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='allegiances',
            field=models.ManyToManyField(blank=True, related_name='members', to='houses.house'),
        ),
        migrations.AddField(
            model_name='character',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='book_characters', to='books.book'),
        ),
        migrations.AddField(
            model_name='character',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='characters.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='characters.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='pov_books',
            field=models.ManyToManyField(blank=True, related_name='book_pov_characters', to='books.book'),
        ),
        migrations.AddField(
            model_name='character',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouses', to='characters.character'),
        ),
    ]
