# Generated by Django 5.0.2 on 2025-04-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['id']},
        ),
    ]
